#!/usr/bin/env python3
"""
hermes pre_tool_call guard: refuse edits to generated evidence files, and refuse
edits at all when the repo has no working oracle.

Wired via config.yaml (alongside guard_installs.py):

  hooks:
    pre_tool_call:
      - command: "<python.exe> <path-to-this-file>"
        matcher: "(?i)(patch|write_file|edit|apply_diff|execute_code|terminal)"
        timeout: 10

Contract: print a JSON block directive to veto, print nothing to allow.
Stdlib only, so it runs under any interpreter.

WHY THIS EXISTS
---------------
A linter the agent can run is a linter the agent can defeat. Observed in a real
session: the model hit "ERROR: no verified command", then

    1. grepped the linter's SOURCE to learn what it reads,
    2. found .agent/facts.json was the data source,
    3. hand-wrote facts.json with a fabricated VERIFIED command,
    4. re-ran the linter and got a pass.

The repository had no working check command at all. Nothing was verified; the
check was simply satisfied. That is Goodhart's law: once a measure becomes a
target, it stops measuring.

The fix is not a better message in the linter. It is to move enforcement
somewhere the agent cannot reach. A hook runs OUTSIDE the model's action space -
it cannot be edited, skipped, or argued with, and its verdict cannot be
manufactured by writing a file.

WHAT IT BLOCKS
--------------
1. Any write to a generated evidence file (.agent/facts.json, graph.json,
   FACTS.md, ARCHITECTURE.md, GRAPH.md). These are outputs of repo_probe.py and
   repo_graph.py. A hand-edit is forgery, not maintenance.
2. Any edit anywhere in a repo whose facts.json fails its integrity check.
3. Any edit in a repo that has a pending worklist but no closure oracle - only
   when ORACLE_REQUIRED is on, which is off by default so the guard is safe to
   install before every repo is set up.
"""
import hashlib
import json
import os
import re
import sys
from pathlib import Path

# Set to "1" to also block edits when a task is pending with no oracle set.
# Off by default: turning it on before your repos have FACTS.md would block
# ordinary work and the guard would get uninstalled, which helps nobody.
ORACLE_REQUIRED = os.environ.get("REPOTOOLKIT_ORACLE_REQUIRED", "0") == "1"

GENERATED = {
    "facts.json", "graph.json",
    "FACTS.md", "ARCHITECTURE.md", "GRAPH.md",
}

WRITE_HINT = re.compile(
    r"""(?ix)
    (?: >{1,2}\s* | \bwrite_text\b | \bopen\s*\([^)]*['"][wa] | \btee\b | \bsed\s+-i\b )
    """
)


def block(reason):
    print(json.dumps({"decision": "block", "reason": reason}))
    sys.exit(0)


def integrity_ok(facts_path: Path) -> bool | None:
    """True/False if checkable, None if there is nothing to check."""
    try:
        data = json.loads(facts_path.read_text(encoding="utf-8", errors="replace"))
    except (OSError, json.JSONDecodeError):
        return None
    stamp = data.get("integrity")
    if not stamp:
        return None
    material = json.dumps(
        {
            "root": data.get("root", ""),
            "interpreters": data.get("interpreters", []),
            "commands": [
                {k: c.get(k) for k in ("role", "command", "status", "evidence")}
                for c in data.get("commands", [])
            ],
        },
        sort_keys=True, separators=(",", ":"),
    )
    return hashlib.sha256(material.encode("utf-8")).hexdigest()[:32] == stamp


def collect_text(tool_input: dict) -> str:
    parts = []
    for key in ("command", "cmd", "script", "code", "input", "path", "file_path",
                "content", "new_string", "old_string"):
        value = tool_input.get(key)
        if isinstance(value, str):
            parts.append(value)
    return " ".join(parts)


def main():
    try:
        payload = json.load(sys.stdin)
    except Exception:
        return  # Malformed input: stay silent rather than block real work.

    tool_input = payload.get("tool_input") or {}
    if not isinstance(tool_input, dict):
        return

    blob = collect_text(tool_input)
    if not blob.strip():
        return

    # --- 1. never let a generated evidence file be written by hand ---------
    #
    # Checked on the raw text so it catches a direct path argument, a shell
    # redirect, and a python open(...,'w') inside execute_code alike.
    for name in GENERATED:
        if name in blob:
            direct_path = any(
                isinstance(tool_input.get(k), str) and tool_input[k].endswith(name)
                for k in ("path", "file_path")
            )
            if direct_path or WRITE_HINT.search(blob):
                block(
                    f"Blocked: '{name}' is GENERATED by repo_probe.py / repo_graph.py "
                    "and must never be written by hand. Editing it forges the evidence "
                    "the oracle depends on and makes every later 'verified' claim false.\n\n"
                    "If it is missing or wrong, regenerate it:\n"
                    "  python <toolkit>/bin/repo_probe.py <repo> --deep\n"
                    "  python <toolkit>/bin/repo_graph.py <repo>\n\n"
                    "If the repo genuinely has no working check command, say so plainly "
                    "and stop. A task with no oracle belongs to the human - that is a "
                    "valid, expected outcome, not a problem to code around."
                )

    # --- 2. refuse to work in a repo whose evidence is already tampered ----
    candidates = []
    for key in ("path", "file_path", "cwd"):
        value = tool_input.get(key)
        if isinstance(value, str) and value.strip():
            candidates.append(value)
    for raw in candidates:
        try:
            start = Path(raw.strip().strip('"').strip("'")).resolve()
        except (OSError, ValueError):
            continue
        for parent in [start, *start.parents]:
            facts = parent / ".agent" / "facts.json"
            if facts.is_file():
                verdict = integrity_ok(facts)
                if verdict is False:
                    block(
                        f"Blocked: {facts} fails its integrity check - it has been "
                        "modified by hand since it was generated. Nothing in it counts "
                        "as evidence.\n\n"
                        "Regenerate before doing any further work:\n"
                        f"  python <toolkit>/bin/repo_probe.py {parent} --deep"
                    )
                if verdict is not None and ORACLE_REQUIRED:
                    worklist = parent / ".agent" / "worklist.txt"
                    closure = parent / ".agent" / "closure.txt"
                    try:
                        pending = bool(worklist.is_file() and
                                       worklist.read_text(encoding="utf-8",
                                                          errors="replace").strip())
                        has_oracle = bool(closure.is_file() and
                                          closure.read_text(encoding="utf-8",
                                                            errors="replace").strip())
                    except OSError:
                        pending = has_oracle = False
                    if pending and not has_oracle:
                        block(
                            "Blocked: this repo has a pending worklist but no closure "
                            "oracle. You cannot prove the task is finished.\n"
                            "  agent-state.sh --repo <repo> closure \"<a VERIFIED "
                            "command from FACTS.md>\""
                        )
                break


main()
